name = "telegram-bot-api-proxy"
main = "src/index.js"
compatibility_date = "2026-01-01"

[env.production]
name = "telegram-bot-api-proxy"
route = { pattern = "api.telegram.388008.xyz/*", zone_name = "telegram.388008.xyz" }
